import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { Locale } from "@/../i18n-config";
import "@/app/globals.css";

import Header from '@/components/topbar/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const  RootLayout = async ({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) => {
  const cookieStore = await cookies()
  const preferredTheme = cookieStore.get('preferredTheme')?.value || 'dim'

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${preferredTheme}`}>
        <Header params={params} />
        {children}
      </body>
    </html>
  );
}

export default RootLayout
