import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar/TopBar";
import getSession from "./auth/session";
import AuthProvider from "@/utilityComponents/AuthProvider";

const geistSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const SessionData = getSession()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased bg-[#1d1d1d]`}>
        
        <AuthProvider SessionData={SessionData}>
          <TopBar />
          <div className="mt-16">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
