import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar/TopBar";

const geistSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased bg-[#1d1d1d]`}>
        <TopBar />
        {children}
      </body>
    </html>
  );
}
